# La siguiente no es necesariamente requerida, se agrega para
# mostrar como funciona.
OBJS = FirstFit.java
OBJS1= GFG.class
OBJS2= GFG
BYNARY= Programas
CFLAG= -g -Wall
all: Programas

Programas: $(OBJS)
	javac  $(OBJS)

run: $(OBJS2)
	java $(OBJS2)

clean:
	rm -f $(BYNARY) $(OBJS1)
