# La siguiente no es necesariamente requerida, se agrega para
# mostrar como funciona.
OBJS = BestFit.java
OBJS1= GFGBEST.class
BYNARY= Programas
CFLAG= -g -Wall
all: Programas

Programas: $(OBJS)
	javac  $(OBJS)

BestFit.o: BestFit.java
	java BestFit

clean:
	rm -f $(BYNARY) $(OBJS1)
